spring:
  application:
    name: FitSync

  datasource:
    url: jdbc:mysql://localhost:3306/fitsync
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  kafka:
#    bootstrap-servers: localhost:9092
