spring:
  application:
    name: FitSync

  datasource:
    url: jdbc:mysql://localhost:3306/fitsync
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/liquibase/master.xml

